#!/usr/bin/env python3
"""
generate_recent_changes.py — CI helper.

Runs `git log` scoped to the content directories (_posts, _activities,
_profiles, _videos, _photos, _kfi) and writes the result as
_data/recent_changes.yml, which recent-changes.html then loops over.

This exists so that anyone with write access to the repo (multiple
people now add content directly through Pages CMS) has a fast, human-
readable way to see what changed recently, without needing to read
raw git history on GitHub -- a lightweight substitute for a formal
review step: not prevention, but fast detection.

Requires the workflow's checkout step to use a fetch-depth deep enough
to cover the window below (see .github/workflows/ci.yml -- shallow
"fetch-depth: 1" checkouts have no history for git log to read at all).
"""
import os
import subprocess
import yaml

CONTENT_PATHS = ["_posts", "_activities", "_profiles", "_videos", "_photos", "_kfi"]
SINCE = "30 days ago"
MAX_COMMITS = 60

SEP = "\x1e"  # record separator, unlikely to appear in a commit subject


def run_git_log():
    cmd = [
        "git", "log",
        f"--since={SINCE}",
        f"--max-count={MAX_COMMITS}",
        f"--pretty=format:{SEP}%H|%ad|%an|%s",
        "--date=short",
        "--name-only",
        "--",
    ] + CONTENT_PATHS
    result = subprocess.run(cmd, capture_output=True, text=True, check=True)
    return result.stdout


def parse(raw):
    commits = []
    for block in raw.split(SEP):
        block = block.strip("\n")
        if not block:
            continue
        lines = block.split("\n")
        header = lines[0]
        sha, date, author, subject = header.split("|", 3)
        files = [f for f in lines[1:] if f.strip()]
        if not files:
            continue
        commits.append({
            "sha": sha[:8],
            "date": date,
            "author": author,
            "subject": subject,
            "files": files,
        })
    return commits


def main():
    raw = run_git_log()
    commits = parse(raw)
    os.makedirs("_data", exist_ok=True)
    with open("_data/recent_changes.yml", "w", encoding="utf-8") as f:
        f.write("# Auto-generated by generate_recent_changes.py during CI.\n")
        f.write("# Do not hand-edit -- next build overwrites this file.\n\n")
        yaml.dump(commits, f, allow_unicode=True, default_flow_style=False, sort_keys=False)
    print(f"Wrote {len(commits)} commits to _data/recent_changes.yml")


if __name__ == "__main__":
    main()
